name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  train-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build & Push Docker Image
      run: |
        docker build -t linear-ml .
        docker tag linear-ml:latest <ECR_URI>:latest
        docker push <ECR_URI>:latest

    - name: Start SageMaker Training
      run: |
        aws sagemaker create-training-job --cli-input-json file://training-job.json

    - name: Deploy Model
      run: |
        aws sagemaker create-endpoint --endpoint-name linear-endpoint \
          --endpoint-config-name linear-endpoint-config
